"""
Django settings for smartedu project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
FILES_DIR = os.path.join(BASE_DIR, 'aizahraa')
print(BASE_DIR)
print(os.path.join(FILES_DIR, 'Dmodel\ '))
# os.path.abspath(os.path.join(BASE_DIR, 'aizahraa'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cjxs7wq0v3rn$k2g98+kzp13oi7f_bi5&c-^rlj00_r*ou72u7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'captcha',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'ckeditor',
    'ckeditor_uploader',
    'crispy_forms',
    'widget_tweaks',
    'bootstrap4',
    'embed_video',
    # my app portal
    'app_users',
    'classroom',
    'module',
    'page',
    'quiz',
    'quizai',
    'question',
    'assignment',
    'completion',
    'notifications',
    'scheduale',
    # chat apps
    'videochat',
    'base',
    'channels',
    'room',
    # api
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
]
CRISPY_TEMPLATE_PACK = 'bootstrap4'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}
# https://www.rootstrap.com/blog/registration-and-authentication-in-django-apps-with-dj-rest-auth/
# ACCOUNT_AUTHENTICATION_METHOD = 'email'
# ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'none'

ROOT_URLCONF = 'smartedu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app_users.views.NavInfo',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartedu.wsgi.application'
ASGI_APPLICATION = 'smartedu.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}
# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# JAZZMIN
JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
}
JAZZMIN_SETTINGS={
    "site_title": "SmartEDU Admin",
    "site_header": "SmartEDU",
    "site_brand": "SmartEDU",
    "welcome_sign": "Welcome to the SmartEDU",
    "copyright": "Acme SmartEDU Ltd",
        "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},

        # external url that opens in a new window (Permissions can be added)
        {"name": "Support", "url": "https://github.com/mohamed-ameer/smartedu", "new_window": True},

        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},

    ],
}

#Login
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'login'

#3rd party apps:
CKEDITOR_UPLOAD_PATH = "uploads/"



# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'smarteduteam88@gmail.com'
EMAIL_HOST_PASSWORD = 'panbdvgbtkoxlljp'

# https://www.youtube.com/watch?v=uVDq4VOBMNM&ab_channel=SysTools

# ,XEm7V,z:x,RfFf
# in-v3.mailjet.com
# EMAIL_BACKEND = 'django_mailjet.backends.MailjetBackend'
# EMAIL_HOST = 'in-v3.mailjet.com'
# MAILJET_API_KEY = "38708dc6c63eab996f7294ddc1384f1a"
# MAILJET_API_SECRET = "bade16bfa393bd9097f4d6570e785e24"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# EMAIL_TIMEOUT = 30
# DEFAULT_FROM_EMAIL = 'mohamed ameer <smarteduteam88@gmail.com>'

# https://www.youtube.com/watch?v=8GNc4Pz4is4&list=LL&index=1&ab_channel=DeveloperBishwas
RECAPTCHA_PUBLIC_KEY = '6Ld4_dogAAAAAL1GBuJiJRWc1cwOiW4n0cVO6-mv'
RECAPTCHA_PRIVATE_KEY = '6Ld4_dogAAAAAKDxYrgAhsBz8u5Et-rj-hgy6-k9'
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']