# Generated by Django 3.2 on 2022-07-11 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_course_modules'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempter',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classroom.course'),
            preserve_default=False,
        ),
    ]
