# Generated by Django 3.2 on 2022-07-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionai',
            name='points',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
