# Generated by Django 3.2 on 2022-07-11 16:30

import assignment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('points', models.PositiveIntegerField()),
                ('assignment_type', models.CharField(choices=[('Regular_File', 'Regular_File'), ('Programming_File', 'Programming_File')], default='Regular_File', max_length=30)),
                ('language_type', models.CharField(choices=[('None', 'None'), ('C', 'C'), ('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python')], default='None', max_length=30)),
                ('dead_time', models.DateTimeField()),
                ('file', models.FileField(blank=True, null=True, upload_to=assignment.models.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=assignment.models.student_directory_path)),
                ('assignment_type', models.CharField(choices=[('Regular_File', 'Regular_File'), ('Programming_File', 'Programming_File')], default='Regular_File', max_length=30)),
                ('language_type', models.CharField(choices=[('None', 'None'), ('C', 'C'), ('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python')], default='None', max_length=30)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentFileContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=assignment.models.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
